server:
  port: 8082

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/travel

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
