server:
  port: 8080

spring:
  application:
    name: gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

logging:
  level:
    org.springframework.cloud.gateway: INFO

spring:
  cloud:
    gateway:
      routes:
        - id: booking-service
          uri: http://localhost:8081
          predicates:
            - Path=/bookings/**, /tours/**, /users/**
        - id: review-service
          uri: http://localhost:8082
          predicates:
            - Path=/reviews/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
