server:
  port: 8081

spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:postgresql://localhost:5432/travel
    username: travel
    password: travel
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env

feign:
  hystrix:
    enabled: false

resilience4j:
  circuitbreaker:
    instances:
      paymentClient:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
