server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://example.com/your-config-repo.git
          default-label: main
          clone-on-start: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
